export const ErrorCodes = {
  // Auth
  EMAIL_IN_USE: "EMAIL_IN_USE",
  EMAIL_REQUIRED: "EMAIL_REQUIRED",
  EMAIL_TOO_LONG: "EMAIL_TOO_LONG",
  INVALID_EMAIL: "INVALID_EMAIL",
  PASSWORD_REQUIRED: "PASSWORD_REQUIRED",
  PASSWORD_TOO_SHORT: "PASSWORD_TOO_SHORT",
  PASSWORD_TOO_LONG: "PASSWORD_TOO_LONG",
  PASSWORD_SAME: "PASSWORD_SAME",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  REFRESH_TOKEN_REQUIRED: "REFRESH_TOKEN_REQUIRED",
  TOKEN_REQUIRED: "TOKEN_REQUIRED",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  EMAIL_ALREADY_VERIFIED: "EMAIL_ALREADY_VERIFIED",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",

  // POI
  POI_NOT_FOUND: "POI_NOT_FOUND",
  POI_NAME_REQUIRED: "POI_NAME_REQUIRED",
  POI_NAME_TOO_LONG: "POI_NAME_TOO_LONG",
  POI_DESCRIPTION_TOO_LONG: "POI_DESCRIPTION_TOO_LONG",
  POI_ADDRESS_TOO_LONG: "POI_ADDRESS_TOO_LONG",
  POI_LATITUDE_INVALID: "POI_LATITUDE_INVALID",
  POI_LONGITUDE_INVALID: "POI_LONGITUDE_INVALID",
  POI_ACCESS_DENIED: "POI_ACCESS_DENIED",

  // Google Place Cache
  GOOGLE_PLACE_NOT_FOUND: "GOOGLE_PLACE_NOT_FOUND",
  GOOGLE_PLACE_FETCH_ERROR: "GOOGLE_PLACE_FETCH_ERROR",
  GOOGLE_PLACE_INVALID_ID: "GOOGLE_PLACE_INVALID_ID",

  // POI List
  LIST_NOT_FOUND: "LIST_NOT_FOUND",
  LIST_NAME_REQUIRED: "LIST_NAME_REQUIRED",
  LIST_NAME_TOO_LONG: "LIST_NAME_TOO_LONG",
  LIST_DESCRIPTION_TOO_LONG: "LIST_DESCRIPTION_TOO_LONG",
  LIST_ACCESS_DENIED: "LIST_ACCESS_DENIED",

  // Saved POI
  SAVED_POI_NOT_FOUND: "SAVED_POI_NOT_FOUND",
  POI_ALREADY_SAVED: "POI_ALREADY_SAVED",
  POI_OR_GOOGLE_PLACE_REQUIRED: "POI_OR_GOOGLE_PLACE_REQUIRED",

  // Generic
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
