export const ErrorCodes = {
  // Auth
  EMAIL_IN_USE: "EMAIL_IN_USE",
  EMAIL_REQUIRED: "EMAIL_REQUIRED",
  INVALID_EMAIL: "INVALID_EMAIL",
  PASSWORD_REQUIRED: "PASSWORD_REQUIRED",
  PASSWORD_TOO_SHORT: "PASSWORD_TOO_SHORT",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  REFRESH_TOKEN_REQUIRED: "REFRESH_TOKEN_REQUIRED",

  // Generic
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
