#!/bin/bash
set -euo pipefail

: "${APP_DB_PASSWORD:?APP_DB_PASSWORD is required}"

psql -v ON_ERROR_STOP=1 \
  --username "$POSTGRES_USER" \
  --dbname "$POSTGRES_DB" \
  -v "app_pass=$APP_DB_PASSWORD" \
  <<-EOSQL
	CREATE ROLE nirby_app WITH LOGIN PASSWORD :'app_pass';
	GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO nirby_app;
	GRANT USAGE ON SCHEMA public TO nirby_app;
	ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_USER} IN SCHEMA public
	  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO nirby_app;
	ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_USER} IN SCHEMA public
	  GRANT USAGE, SELECT ON SEQUENCES TO nirby_app;
EOSQL